apiVersion: v1
kind: Service
metadata:
  name: deepwatermap-ui
spec:
  type: NodePort
  selector:
    app: deepwatermap-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
